name: Deployment with CI CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: lint
        run: make lint
      - name: test
        run: make test

  DeployDev:
    name: Deploy to Dev
    if: github.event_name == 'pull request'
    needs: [build]
    runs-on: ubuntu-latest
    environment:
      name: Development
    steps:
      - name: Checkout
        uses: actions/checkout@master

      # Setup gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_email: ${{ secrets.GCP_EMAIL }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          export_default_credentials: true

      # Configure Docker with Credentials
      - name: Configure Docker
        run: |
          gcloud auth configure-docker

      # Build the Docker image
      - name: Build & Publish
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT }}
          gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_APPLICATION }}
          gcloud config set run/region us-central1

      # Deploy the Docker image to the GKE cluster
      - name: Deploy
        run: |
          gcloud run deploy ${{ secrets.GCP_APPLICATION }} --image gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_APPLICATION }} \
          --platform managed \
          --allow-unauthenticated \
          --memory 512M

  DeployStaging:
    name: Deploy to Staging
    if: github.event.ref == 'refs/heads/main'
    needs: [build]
    runs-on: ubuntu-latest
    environment:
      name: Staging
    steps:
      - name: Deploy
        run: echo I am deploying to staging

  DeployProd:
    name: Deploy to Production
    needs: [DeployStaging]
    runs-on: ubuntu-latest
    environment:
      name: Production
      url:
    steps:
      - name: Deploy
        run: echo I am deploying to prod
